### ISSUE TITLE
GPIO Analog mode

### ISSUE THREAD

**Issue by ghost** [mnemocron/STM32-Tutorial#2]
Hello, 

I would like to ask a question regarding read analog value.
I am using STM32F105 which pin PB10 is connected to an analog signal, and I want to monitor the value. The PB10 can be configured as GPIO_input/output/analog and not ADC mode. 

Is there anyway to read the analog value from this pin?

**Comment by mnemocron** [comment]
Hi
I think you answered your own question.
>  and not ADC mode.

So: no, PB10 cannot read an analog signal
You have to connect the signal to another pin which has ADC capability.

**Comment by ghost** [comment]
Thank you @mnemocron
