### ISSUE TITLE
I2C PCA9685

### ISSUE THREAD

**Issue by rbeekhuijzen** [mnemocron/STM32-Tutorial#3]
Is the project for PCA9685 available? I've tried to run the code in the PDF but it didn't run.
Thanks in advance,
Robert

**Comment by mnemocron** [comment]
Hi, not unfortunately the PDFs are really old. Maybe the HAL has changed in the meantime. Anyhow, I don't have the project for this code anymore. 
Maybe you can check out the github search and look for something like "pca9685 stm32". 
On the quick I found the following examples:
- https://github.com/henriheimann/stm32-hal-pca9685
- https://github.com/lamik/PCA9685_Servo_STM32_HAL
